[template]
src = "node-exporter.sh.tmpl"
dest = "/opt/app/current/bin/tmpl/node-exporter.sh"
mode = "0700"
keys = [
  "/",
]
reload_cmd = "/opt/app/current/bin/tmpl/node-exporter.sh;appctl refreshDynamicService node_exporter"