---
- name: Install OS plugins - {{ opts.name }}
  shell: |
    extra_url1="https://github.com/aparo/opensearch-analysis-ik/releases/download/{{ opensearch_version }}/opensearch-analysis-ik-{{ opensearch_version }}.zip"
    extra_url2="https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/{{ opensearch_exporter_version }}/prometheus-exporter-{{ opensearch_exporter_version }}.zip"
    realname="{{ opts.name }}"
    res=$(/opt/opensearch/current/bin/opensearch-plugin list | grep "$realname" | wc -l)
    if [ "$res" -eq 1 ]; then exit 0; fi
    if [ "$realname" = "opensearch-analisys-ik" ]; then
      realname="$extra_url1"
    elif [ "$realname" = "prometheus-exporter" ]; then
      realname="$extra_url2"
    fi
    OPENSEARCH_HOME=/opt/opensearch/current OPENSEARCH_JAVA_HOME=/opt/opensearch/current/jdk OPENSEARCH_PATH_CONF=/opt/app/current/conf/opensearch /opt/opensearch/current/bin/opensearch-plugin install -v --batch "$realname"
  register: installed
  ignore_errors: True