---
- name: install node exporter binaries
  include_role:
    name: install-1.0.6
  vars:
    opts:
      pkg_name: node_exporter
      pkg_version: "{{ node_exporter_version }}"
      pkg_url: https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ arch1 }}.tar.gz
      pkg_type: tar.gz
      creates: bin
      extracts: yes
      extra_opts:
        - "--strip-components=1"

- name: group svc
  group:
    name: svc
    state: present

- name: User - opensearch
  user:
    name: opensearch
    groups: svc
    shell: /usr/sbin/nologin
    create_home: no
    append: yes
    state: present

- name: User - prometheus
  user:
    name: prometheus
    groups: svc
    shell: /usr/sbin/nologin
    create_home: no
    append: yes
    state: present

- name: install opensearch binaries
  include_role:
    name: install-1.0.6
  vars:
    opts:
      pkg_name: opensearch
      pkg_version: "{{ opensearch_version }}"
      pkg_url: https://artifacts.opensearch.org/releases/bundle/opensearch/{{ opensearch_version }}/opensearch-{{ opensearch_version }}-linux-x64.tar.gz
      pkg_type: tar.gz
      creates: bin
      extracts: yes
      extra_opts:
        - "--strip-components=1"

- name: jdk file permission
  file:
    path: '/opt/opensearch/current/jdk'
    mode: o+rX
    state: directory
    recurse: yes

- name: copy opensearch initial config
  copy:
    src: /opt/opensearch/current/config/
    dest: /opt/app/current/conf/opensearch
    owner: root
    group: svc
    mode: g+w
    remote_src: yes

- name: copy more configuration files
  copy:
    src: opt/app/conf/
    dest: /opt/app/current/conf
    owner: root
    group: svc
    mode: g+w

# - name: install plugins
#   include_tasks: install-plugin2.yml
#   loop:
#     - name: analysis-icu
#     - name: analysis-kuromoji
#     - name: analysis-nori
#     - name: analysis-phonetic
#     - name: analysis-smartcn
#     - name: analysis-stempel
#     - name: analysis-ukrainian
#     - name: mapper-annotated-text
#     - name: mapper-murmur3
#     - name: mapper-size
#     - name: opensearch-analisys-ik
#     - name: repository-hdfs
#     - name: repository-s3
#     - name: ingest-attachment
#     - name: prometheus-exporter
#   loop_control:
#     loop_var: opts
- name: fix analysis-ik config path
  file:
    src: /opt/app/current/conf/opensearch/opensearch-analysis-ik
    dest: /opt/app/current/conf/opensearch/analysis-ik
    owner: root
    group: svc
    state: link

- name: prepare dict directory
  file:
    path: /opt/app/current/conf/opensearch/analysis-ik/custom
    owner: opensearch
    owner: root
    group: svc
    state: directory

- name: check if jieba dic exists
  stat:
    path: "{{ role_path }}/files/tmp/jieba.dic"
  register: jieba_dic
  delegate_to: localhost

- name: download jieba dict
  get_url:
    url: "https://github.com/QingCloudAppcenter/elk-archived/raw/master/docker-image/standard/elasticsearch/dicts/jieba.dic"
    dest: "{{ role_path }}/files/tmp/jieba.dic"
  delegate_to: localhost
  when: jieba_dic.stat.exists == False

- name: copy jieba dict
  copy:
    src: "{{ role_path }}/files/tmp/jieba.dic"
    dest: "/opt/app/current/conf/opensearch/analysis-ik/custom"
    owner: root
    group: svc

- name: check if commons-logging-1.3.2-bin.tar.gz exists
  stat:
    path: "{{ role_path }}/files/tmp/commons-logging-1.3.2-bin.tar.gz"
  register: commons_logging
  delegate_to: localhost

- name: download commons-logging-1.3.2-bin.tar.gz
  get_url:
    url: "https://dlcdn.apache.org//commons/logging/binaries/commons-logging-1.3.2-bin.tar.gz"
    dest: "{{ role_path }}/files/tmp/commons-logging-1.3.2-bin.tar.gz"
  delegate_to: localhost
  when: commons_logging.stat.exists == False

- name: unarchive commons-logging-1.3.2-bin.tar.gz
  unarchive:
    src: "files/tmp/commons-logging-1.3.2-bin.tar.gz"
    dest: "/opt/opensearch/current/plugins/opensearch-analysis-ik"
    owner: root
    group: svc
    mode: "0644"
    extra_opts:
      - "--strip-components=1"
      - "commons-logging-1.3.2/commons-logging-1.3.2.jar"

- name: fix internal_users.yml
  shell: |
    fn="/opt/app/current/conf/opensearch/opensearch-security/internal_users.yml"
    adminLine=$(awk '/admin/{print NR; exit}' $fn)
    reservedLine=$(awk -v n=$adminLine 'NR>n && /reserved/{print NR; exit}' $fn)
    sed -i "${reservedLine}s/.*/  reserved: false/" $fn