app_version: v1.3.0
opensearch_version: 2.3.0
opensearch_exporter_version: 2.3.0.0
package_version: 2.3.0
opensearch_dashboards_version: 2.3.0
opensearch_dashboards_package_version: 2.3.0
logstash_version: 7.16.3
node_exporter_version: 1.4.0
arch1: amd64
local_cache_path: /root/.ansible/cache