app_version: 1.3.0
appAgentVersion: v1.0.7
arping_version: "20211215-1"
opensearch_version: 2.19.1
caddy_version: v2.9.1
jq_version: "1.7.1"
openjdk_version: "21.0.2"
opensearch_dashboards_version: 2.19.1
haproxy_version: 3.0.9
keepalived_version: 2.3.3
logstash_version: 8.17.4
node_exporter_version: 1.9.1
cerebro_version: 0.9.4
ubuntu_22_amd64_kernel: 5.15.0-136-generic