---
- name: set up variables
  set_fact:
    node_exporter_version: "{{ node_exporter_version | d('1.8.2') }}"
    arch: "{{ arch | d(default_arch) }}"
    installPath: "/opt/prometheus/node_exporter"

- name: group svc
  group:
    name: svc
    state: present

- name: Add the prometheus Service User
  user:
    name: "prometheus"
    groups: "svc"
    shell: /sbin/nologin
    create_home: no
    home: /var/lib/prometheus
    append: yes
    comment: "prometheus Service User"
    state: present

# will set var downloaded
- include_role:
    name: downloader
  vars:
    opts:
      pkg_name: node-exporter
      pkg_version: "{{ node_exporter_version }}"
      pkg_feature: "linux-{{ arch }}"
      pkg_fileType: ".tgz"
      pkg_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz"

- name: Create node_exporter folder
  file:
    path: "{{ installPath }}/{{ node_exporter_version }}"
    state: directory

- name: link for current
  file:
    src: "{{ installPath }}/{{ node_exporter_version }}"
    dest: "{{ installPath }}/current"
    state: link

- name: decompress file
  unarchive:
    src: "{{ downloaded }}"
    dest: "{{ installPath }}/{{ node_exporter_version }}"
    creates: "{{ installPath }}/{{ node_exporter_version }}/node_exporter"
    extra_opts:
    - --strip-components=1

- name: Copy files
  copy:
    src: "opt/app/current/conf/systemd/node_exporter.service"
    dest: /opt/app/current/conf/systemd
    owner: root
    group: root
    mode: preserve