---
- name: install confd files
  include_role:
    name: confd-files-1.1.0

- name: copy shell script
  copy:
    src: opt/app/bin/node/
    dest: /opt/app/current/bin/node
    owner: root
    group: svc
    mode: preserve

- name: fix directory permission for app conf
  file:
    path: /opt/app/current/conf
    group: svc
    mode: g+rx
    state: directory
