---
- name: common setup
  hosts: all
  vars:
    target_env: "{{ lookup('env', 'target') }}"
  vars_files:
  #- /root/.qcacode
  strategy: free
  roles:
  - os-kernel
  - app-agent
  - appctl-1.3.0
  - appctl-fix
  - arping
  - common
  - caddy
  - disable-package-manager-timers
  - disable-motd

  tasks:
  - include_role:
      name: "{{ svc_name }}"
    when: "'opensearch' in group_names"
    loop:
    - jq
    - node-exporter
    - opensearch
    - opensearch-plugins
    - node-opensearch
    loop_control:
      loop_var: svc_name

  - include_role:
      name: "{{ svc_name }}"
    when: "'logstash' in group_names"
    loop:
    - jq
    - logstash
    - logstash-plugins
    - node-logstash
    loop_control:
      loop_var: svc_name

  - include_role:
      name: "{{ svc_name }}"
    when: "'opensearchDashboards' in group_names"
    loop:
    - lualib
    - openjdk
    - cerebro
    - opensearchDashboards
    - haproxy
    - keepalived
    - node-opensearchDashboards
    loop_control:
      loop_var: svc_name
