---
- name: common setup
  hosts: all
  vars:
    target_env: "{{ lookup('env', 'target') }}"
  vars_files:
  #- /root/.qcacode
  strategy: free
  roles:
  - app-agent-1.1.1
  - appctl-1.3.0
  - arping-1.0.5
  - common
  - role: caddy-1.1.8
    vars:
      caddy_plugins: upload
  - update-apt-sources-1.0.0
  - disable-apt-jobs-1.0.0
  - disable-motd-1.0.0

  tasks:
  - include_role:
      name: "{{ svc_name }}"
    when: "'opensearch' in group_names"
    loop:
    - opensearch
    - jq-1.0.9
    - node-opensearch
    loop_control:
      loop_var: svc_name

  - include_role:
      name: java-1.0.1
    vars:
      java_version: 8
    when: ('logstash' in group_names) or ('opensearchDashboards' in group_names) or ('' in group_names)

  - include_role:
      name: "{{ svc_name }}"
    when: "'logstash' in group_names"
    loop:
    - logstash
    - node-logstash
    loop_control:
      loop_var: svc_name

  - include_role:
      name: "{{ svc_name }}"
    when: "'opensearchDashboards' in group_names"
    loop:
    # - opensearchDashboards
    # - nodejs-1.0.0
    # - haproxy-1.0.8
    # - keepalived-1.0.6
    - node-opensearchDashboards
    loop_control:
      loop_var: svc_name
