---
- name: set variables
  set_fact:
    ls_home: /opt/logstash/current

- name: group svc
  group:
    name: svc
    state: present

- name: User - logstash
  user:
    name: logstash
    groups: svc
    shell: /usr/sbin/nologin
    create_home: no
    append: yes
    state: present

- name: install logstash binaries
  include_role:
    name: install-1.0.6
  vars:
    opts:
      pkg_name: logstash
      pkg_version: "{{ logstash_version }}"
      pkg_url: https://artifacts.opensearch.org/logstash/logstash-oss-with-opensearch-output-plugin-{{ logstash_version }}-linux-x64.tar.gz
      pkg_type: tar.gz
      creates: bin
      extracts: yes
      extra_opts:
        - "--strip-components=1"

- name: copy default config
  copy:
    src: /opt/logstash/current/config/
    dest: /opt/app/current/conf/logstash
    owner: root
    group: svc
    mode: g+w
    remote_src: yes

# - name: prepare plugins
#   include_tasks: install-plugin.yml
#   loop:
#   - name: logstash-input-irc
#     version: 3.0.7
#   - name: logstash-input-log4j
#     version: 3.1.3
#   - name: logstash-input-xmpp
#     version: 3.1.7
#   - name: logstash-output-irc
#     version: 3.0.6
#   - name: logstash-output-statsd
#     version: 3.2.0
#   - name: logstash-output-xmpp
#     version: 3.0.8
#   loop_control:
#     loop_var: opts

- name: copy configuration files
  copy:
    src: opt/app/conf/logstash/
    dest: /opt/app/current/conf/logstash
    owner: root
    group: svc
    mode: preserve

- name: install service
  copy:
    src: lib/systemd/system/
    dest: /opt/app/current/conf/systemd
    owner: root
    group: svc
    mode: preserve

# - name: add logstash bin dir to system-wide path
#   copy:
#     dest: /etc/profile.d/logstash-path.sh
#     content: 'PATH=$PATH:{{ ls_home }}/bin'
